languageCode = "en-us"
title = "My Hyper Hugo Site"
baseurl = "https://lecturer-angelina-25845.netlify.com"
theme = "HST"

disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 3

[params]
	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "Hyperstatic"
	description = "My Hugo Website"
	author = "Nagib Tharani"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

[params.social]
	twitter = "gohyperstatic"
	author = "nagibtharani"
	facebook_admin = ""
	facebook_author = "nagib.tharani"
	facebook = "nagib.tharani"
	facebook_app_id = ""


	# Set menu = "main" on static pages front matter. 
	# Only set menu.main categories for sections like "Blog" that have markdown content below.

SectionPagesMenu = "main"

[[menu.main]]
    name = "Blog"
    weight = -110
    identifier = "blog"
    url = "/blog/"
