languageCode = "en-us"
title = "My Hyper Hugo Site"
baseurl = "/"
theme = "HST"

disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
  # information about you and your website.
	name = "Hyperstatic"
	description = "My Hugo Website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"


[params.social]
	twitter = "gohyperstatic"
	author = "nagibtharani"
	facebook_admin = ""
	facebook_author = "nagib.tharani"
	facebook = "nagib.tharani"
	facebook_app_id = ""
