name = "HST"
license = "MIT"
licenselink = "https://github.com/ntharani/HST-Materialize-Hugo/blob/master/LICENSE"
description = "Simple Co - Hugo MaterializeCSS Theme with WebPack 2 Build Scripts"
homepage = "http://siteforthistheme.com/"
tags = []
features = []
min_version = 0.19

[author]
  name = "Nagib Tharani"
  homepage = "https://www.nagibtharani.com"